**difference loc and iloc?**

**loc[]:**
loc is used to find the certain data from rows and columns labels.


**iloc[]:**
is used to access certain data through integer positions.

**how do you check for and count missing values in DataFrame**

isnull().sum()

**Filter rows where both conditions are true?**

AND(&) operation is used to filter rows because both conditions are true.

**Difference b\w count df.copy() & just assigning df2 = df?**

df.copy():
df.copy is used make a exact copy of dataset.

df2 = df:
in it the dataset which is stored in df is assigned to df2.

In [1]:
import pandas as pd
df= pd.read_csv("/content/Amazon.csv")
df

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3.0,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1.0,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3.0,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5.0,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2.0,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12063,ORD0012064,2021-03-01,CUST016232,Priya Kapoor,P00018,Vacuum Cleaner,Electronics,Apex,1.0,504.62,0.00,25.23,4.71,534.56,Debit Card,Returned,Dallas,TX,India,SELL00564
12064,ORD0012065,2023-01-29,CUST018841,Ritika Singh,P00002,Bluetooth Speaker,Home & Kitchen,UrbanStyle,1.0,274.12,0.00,13.71,6.44,294.27,Debit Card,Delivered,New York,NY,India,SELL01542
12065,ORD0012066,2024-04-13,CUST025141,Aditya Mehta,P00010,Smartwatch,Sports & Outdoors,CoreTech,4.0,443.77,0.05,84.32,4.73,1775.38,Debit Card,Delivered,Los Angeles,CA,United States,SELL01487
12066,ORD0012067,2021-09-30,CUST009609,Priya Sharma,P00007,Mechanical Keyboard,Sports & Outdoors,KiddoFun,4.0,184.56,0.00,59.06,7.25,804.55,Net Banking,Delivered,Seattle,WA,Australia,SELL00367
12067,ORD0012068,2022-04-29,CUST041204,Vivaan Mehta,P00036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**1. Total Sales of company?**

In [2]:
total_sales = df['TotalAmount'].sum()

print("Total Sales:", total_sales)

Total Sales: 11066316.6

**2. Which category of product made high sales?**

In [3]:
category_sales = df.groupby('Category')['TotalAmount'].sum().sort_values(ascending=False)
category_sales

Category
Electronics          1904397.58
Sports & Outdoors    1872723.55
Toys & Games         1868566.73
Books                1835290.54
Home & Kitchen       1793283.17
Clothing             1792055.03
Name: TotalAmount, dtype: float64

**3. Checking Which Country generate highest sales?**

In [22]:
country_sales = df.groupby('Country')['TotalAmount'].sum().sort_values(ascending=False)
country_sales

Country
United States     7786425.67
India             1695272.92
Canada             645051.53
United Kingdom     532122.38
Australia          407444.10
Name: TotalAmount, dtype: float64

**4. Commonly Used payment method in customers?**

In [6]:
payment_method = df['PaymentMethod'].value_counts()
payment_method

PaymentMethod
Credit Card         4154
Debit Card          2491
Amazon Pay          1825
UPI                 1809
Net Banking         1194
Cash on Delivery     594
Name: count, dtype: int64

**5. Find the average order value?**

In [11]:
average_order = df['TotalAmount'].mean().astype(int)
average_order

np.int64(917)

**6. Which is generate highest sale in company?**

In [14]:
top_product = df.groupby('ProductName')['TotalAmount'].sum().sort_values(ascending=False).head(10)
top_product

ProductName
Puzzle 1000pc        265311.98
Winter Jacket        256215.43
Smartphone Case      253820.50
Memory Card 128GB    252283.21
Water Bottle         246356.94
Vacuum Cleaner       243841.87
Smartwatch           243566.25
Electric Kettle      241700.57
Projector Mini       240893.14
Cookware Set         239944.61
Name: TotalAmount, dtype: float64

**7. Which Brand make highest sales?**

In [15]:
Brand_name = df.groupby('Brand')['TotalAmount'].sum().sort_values(ascending=False).head(10)
Brand_name

Brand
UrbanStyle    1143132.80
KiddoFun      1136378.46
CoreTech      1130775.07
Zenith        1111749.71
ReadMore      1110072.01
FitLife       1108972.97
HomeEase      1096051.16
Apex          1091928.46
BrightLux     1085685.30
NexPro        1051570.66
Name: TotalAmount, dtype: float64

**8. How much order returned or canceled?**

In [21]:
returned_orders = (df['OrderStatus'] == 'Returned').sum()

cancelled_orders = (df['OrderStatus'] == 'Cancelled').sum()

print(returned_orders)

print(cancelled_orders)

398
375