<a href="https://colab.research.google.com/github/RidaFatima1467/Academy-work/blob/main/day4_pandas_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import libraries**

In [6]:
import pandas as pd

**Load Csv file used in previous Question**

In [7]:
df = pd.read_csv("/content/tested-selected-columns.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875
...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583

**identify missing values**

In [8]:
df.isnull().sum()

PassengerId     0
Survived        0
Pclass          0
Name            0
Sex             0
Age            86
SibSp           0
Parch           0
Ticket          0
Fare            1
dtype: int64

**Handle missing values**

In [9]:
df["Age"] = df["Age"].fillna(df["Age"].median())

df["Fare"] = df["Fare"].fillna(df["Fare"].median())

In [10]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
dtype: int64

**checking datatypes**

In [14]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
dtype: object

**Removing duplicates**

In [19]:
df = df.drop_duplicates()

**Adding Dataframe**

In [20]:
class_info = pd.DataFrame({
    "Pclass": [1, 2, 3],
    "Class_Label": ["Premium", "Standard", "Economy"]
})

class_info

   Pclass Class_Label
0       1     Premium
1       2    Standard
2       3     Economy

**merging with dataset**

In [23]:
df.merge(class_info)

UnboundLocalError: cannot access local variable 'lidx' where it is not associated with a value