**What is the difference between .drop() and .dropna()?**

.drop()is used to delete the specific row and column.

.dropna() is used to drop the row and column which contain null values.

**How do you change the dtype of a column — and when would you need to?**

 By using **astype** we can change the dtype of the column. we can change the dtype when the column values are in float and we need them in integer then we need it.
 For example: age must be in integer values. if in age column float values present we can apply astype to change it into integer.

**What does .apply() do and how is it different from vectorized operations?**

.apply() can run a function on values like a loop. whereas the vectorized operation perform function or operation on entire array at once.

.apply() is used for complex operations or calculations also work slowly  whereas the vectorized operations perform simple calculations and is fast.

**Difference between .pivot() and .pivot_table()?**

.pivot() is used to reshape the entire data but it doesn't handle the duplicates and null values.

.pivot_table is also to reshape the data but it can handle the missing values as well using aggregation operations like mean,median etc.

**What does .merge() do and what are the 4 types of joins?**

.merge() is used to combine dataframes or datasets.

1. inner join:
 It is used to join or combine the same data of both the dataframes or datasets.

 2. left join:
  It will combine all the data of the left dataframes and combine the entities which are same in left dataframe and the right dataframe.

  3. right join:
  complete right dataframe or dataset and matching entities in both left and right dataframe.

  4. outer join:
  combine both the datasets or dataframes completely.

**Implementation Task**

**Import libraries**

In [2]:
import pandas as pd

**Load amazon csv file**

In [3]:
df = pd.read_csv("/content/Amazon.csv")
df

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD0099996,2023-03-07,CUST001356,Karan Joshi,P00047,Memory Card 128GB,Electronics,Apex,2,492.34,0.00,78.77,2.75,1066.20,UPI,Delivered,Jacksonville,FL,India,SELL00041
99996,ORD0099997,2021-11-24,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,0.00,179.72,6.07,2432.29,Credit Card,Delivered,San Jose,CA,United States,SELL01449
99997,ORD0099998,2023-04-29,CUST012579,Aman Gupta,P00030,Dress Shirt,Sports & Outdoors,BrightLux,4,232.40,0.00,74.37,12.43,1016.40,Cash on Delivery,Delivered,Indianapolis,IN,United States,SELL00028
99998,ORD0099999,2021-11-01,CUST026243,Simran Gupta,P00046,Car Charger,Sports & Outdoors,HomeEase,1,294.05,0.00,23.52,13.09,330.66,Debit Card,Delivered,Charlotte,NC,United States,SELL00324
99999,ORD0100000,2021-12-04,CUST029492,Sunita Reddy,P00019,LED Desk Lamp,Home & Kitchen,CoreTech,5,166.70,0.05,63.35,3.34,858.52,Debit Card,Delivered,New York,NY,United States,SELL00761

**Identify missing values**

In [4]:
df.isnull().sum()

OrderID          0
OrderDate        0
CustomerID       0
CustomerName     0
ProductID        0
ProductName      0
Category         0
Brand            0
Quantity         0
UnitPrice        0
Discount         0
Tax              0
ShippingCost     0
TotalAmount      0
PaymentMethod    0
OrderStatus      0
City             0
State            0
Country          0
SellerID         0
dtype: int64

There are no missing values are present in dataset if present then drop the rows if row is not necessary otherwise filled with mean, median,mode,backward fill etc.

**Check datatypes**

In [6]:
df.dtypes

OrderID           object
OrderDate         object
CustomerID        object
CustomerName      object
ProductID         object
ProductName       object
Category          object
Brand             object
Quantity           int64
UnitPrice        float64
Discount         float64
Tax              float64
ShippingCost     float64
TotalAmount      float64
PaymentMethod     object
OrderStatus       object
City              object
State             object
Country           object
SellerID          object
dtype: object

**fixing datatypes**

In [9]:
# coverting datetime column
df["OrderDate"] = pd.to_datetime(df["OrderDate"], errors="coerce")

#ensuring numeric columns are in numeric form or not
numeric_columns = [
    "Quantity", "UnitPrice", "Discount", "Tax",
    "ShippingCost", "TotalAmount"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print("\nData types after fixing:")
print(df.dtypes)

Data types after fixing:
OrderID                  object
OrderDate        datetime64[ns]
CustomerID               object
CustomerName             object
ProductID                object
ProductName              object
Category                 object
Brand                    object
Quantity                  int64
UnitPrice               float64
Discount                float64
Tax                     float64
ShippingCost            float64
TotalAmount             float64
PaymentMethod            object
OrderStatus              object
City                     object
State                    object
Country                  object
SellerID                 object
dtype: object

**Removing Duplicates**

In [14]:
df.duplicated().sum()

np.int64(0)

**Creating to derived columns**
1. GrossSales = Quantity*UnitPrice
sale value before discount,tax etc
2. DiscountAmount = GrossSales*Discount
convert acutal discount percentage into actual money

In [16]:
df["GrossSales"] = df["Quantity"] * df["UnitPrice"]
df["DiscountAmount"] = df["GrossSales"] * df["Discount"]

df[[
    "Quantity", "UnitPrice", "Discount",
    "GrossSales", "DiscountAmount"
]]

       Quantity  UnitPrice  Discount  GrossSales  DiscountAmount
0             3     106.59      0.00      319.77          0.0000
1             1     251.37      0.05      251.37         12.5685
2             3      35.03      0.10      105.09         10.5090
3             5      33.58      0.15      167.90         25.1850
4             2     515.64      0.25     1031.28        257.8200
...         ...        ...       ...         ...             ...
99995         2     492.34      0.00      984.68          0.0000
99996         5     449.30      0.00     2246.50          0.0000
99997         4     232.40      0.00      929.60          0.0000
99998         1     294.05      0.00      294.05          0.0000
99999         5     166.70      0.05      833.50         41.6750

[100000 rows x 5 columns]

**Reshape data by groupby and aggregation**

Grouping by category helps the business compare the performance of diiferent category of products.

In [17]:
category_summary = (
    df.groupby("Category")
      .agg(
          OrderCount=("OrderID", "count"),
          TotalQuantity=("Quantity", "sum"),
          TotalGrossSales=("GrossSales", "sum"),
          TotalDiscount=("DiscountAmount", "sum"),
          AverageOrderAmount=("TotalAmount", "mean")
      )
      .reset_index()
)

category_summary

,Category,OrderCount,TotalQuantity,TotalGrossSales,TotalDiscount,AverageOrderAmount
0,Books,16752,49981,15129134.02,1.132719e+06,911.045667
1,Clothing,16439,49523,15126422.24,1.127570e+06,927.878673
2,Electronics,16853,50696,15432682.26,1.144068e+06,924.714720
3,Home & Kitchen,16610,49624,15030780.21,1.128609e+06,912.940359
4,Sports & Outdoors,16804,50543,15214315.21,1.132323e+06,913.209467
5,Toys & Games,16542,49773,15087879.05,1.117829e+06,919.881815

**Creating dataframe and merging it with dataset**

In [19]:
#new DataFrame
category_info = pd.DataFrame({
    'Category': ['Electronics', 'Clothing', 'Furniture', 'Beauty'],
    'Category_Type': ['Technology', 'Fashion', 'Home', 'Personal Care']
})

# Merge with the dataset
df = df.merge(category_info, on='Category', how='left')
df

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,...,PaymentMethod,OrderStatus,City,State,Country,SellerID,GrossSales,DiscountAmount,Category_Type_x,Category_Type_y
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,...,Debit Card,Delivered,Washington,DC,India,SELL01967,319.77,0.0000,NaN,NaN
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,...,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298,251.37,12.5685,NaN,NaN
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,...,Debit Card,Delivered,Austin,TX,United States,SELL00908,105.09,10.5090,Fashion,Fashion
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,...,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164,167.90,25.1850,NaN,NaN
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,...,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411,1031.28,257.8200,Fashion,Fashion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD0099996,2023-03-07,CUST001356,Karan Joshi,P00047,Memory Card 128GB,Electronics,Apex,2,492.34,...,UPI,Delivered,Jacksonville,FL,India,SELL00041,984.68,0.0000,Technology,Technology
99996,ORD0099997,2021-11-24,CUST031254,Sunita Kapoor,P00046,Car Charger,Sports & Outdoors,Apex,5,449.30,...,Credit Card,Delivered,San Jose,CA,United States,SELL01449,2246.50,0.0000,NaN,NaN
99997,ORD0099998,2023-04-29,CUST012579,Aman Gupta,P00030,Dress Shirt,Sports & Outdoors,BrightLux,4,232.40,...,Cash on Delivery,Delivered,Indianapolis,IN,United States,SELL00028,929.60,0.0000,NaN,NaN
99998,ORD0099999,2021-11-01,CUST026243,Simran Gupta,P00046,Car Charger,Sports & Outdoors,HomeEase,1,294.05,...,Debit Card,Delivered,Charlotte,NC,United States,SELL00324,294.05,0.0000,NaN,NaN
99999,ORD0100000,2021-12-04,CUST029492,Sunita Reddy,P00019,LED Desk Lamp,Home & Kitchen,CoreTech,5,166.70,...,Debit Card,Delivered,New York,NY,United States,SELL00761,833.50,41.6750,NaN,NaN