In [337]:
import pandas as pd
import numpy as np

In [338]:
df1 = pd.read_csv("/content/afl_players_info_raw.csv")
df1

,id,player_name,player_full_name,first_name,last_name,born_date,debut_date,debut_age,last_date,last_age,height,weight,profile_pic,player_link,player_common_names,player_teams
0,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,200,100,NaN,https://afltables.com/afl/stats/players/R/Ryan...,NaN,"{Geelong Cats,St Kilda Saints}"
1,43262,Gary Ablett,Gary_Ablett1,Gary,Ablett,1984-05-14,2002-03-30,17,2020-10-24,36,182,87,NaN,https://afltables.com/afl/stats/players/G/Gary...,NaN,"{Geelong Cats,Gold Coast Suns}"
2,43276,Leek Aleer,Leek_Aleer,Leek,Aleer,2001-08-21,2022-07-30,20,2025-09-06,24,195,85,https://res.cloudinary.com/dijzdikkh/image/upl...,https://afltables.com/afl/stats/players/L/Leek...,NaN,NaN
3,43264,Nathan Ablett,Nathan_Ablett,Nathan,Ablett,1985-12-13,2005-08-12,19,2011-08-28,25,195,95,NaN,https://afltables.com/afl/stats/players/N/Nath...,NaN,"{Geelong Cats,Gold Coast Suns}"
4,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,196,101,NaN,https://afltables.com/afl/stats/players/C/Cain...,NaN,"{Carlton Blues,Port Adelaide Power,St Kilda Sa..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2843,43659,Charlie Curnow,Charlie_Curnow,charlie,CURNOW,1997-02-03,2016-04-03,19,2025-07-24,28,192,96,https://res.cloudinary.com/dijzdikkh/image/upl...,https://afltables.com/afl/stats/players/C/Char...,NaN,{Carlton Blues}
2844,44352,Matt Maguire,Matt_Maguire,matt,MAGUIRE,1984-05-30,2002-05-03,17,2015-04-18,30,192,101,NaN,https://afltables.com/afl/stats/players/M/Matt...,NaN,"{Brisbane Lions,St Kilda Saints}"
2845,45045,Cam Sutcliffe,Cam_Sutcliffe,cam,SUTCLIFFE,1992-05-23,2012-07-08,20,2020-09-05,28,186,87,NaN,https://afltables.com/afl/stats/players/C/Cam_...,NaN,"{Fremantle Dockers,Port Adelaide Power}"
2846,45738,Mark McVeigh,Mark_McVeigh,mark,MCVEIGH,1981-01-26,1999-03-25,18,2012-05-26,31,184,85,NaN,https://afltables.com/afl/stats/players/M/Mark...,NaN,{Essendon Bombers}
2847,44919,Dylan Shiel,Dylan_Shiel,dylan,SHIEL,1993-03-09,2012-03-23,19,2025-08-27,32,182,83,NaN,https://afltables.com/afl/stats/players/D/Dyla...,NaN,NaN

In [339]:
df2 = pd.read_csv("/content/afl_players_seasonal_stats_raw.csv")
df2

/tmp/ipykernel_2055/4247589376.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv("/content/afl_players_seasonal_stats_raw.csv")

,player_id,year,team,is_finals,games_played,kicks,marks,handballs,disposals,goals,...,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_marks_inside_50,avg_one_percenters,avg_bounces,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played
0,43261,2018,Geelong Cats,False,3,17.0,9.0,21.0,38.0,3.0,...,6.7,6.7,0.3,1.7,4.3,0.0,0.3,6.7,92.7,84.3
1,43261,2018,Geelong Cats,True,1,3.0,2.0,2.0,5.0,0.0,...,2.0,3.0,1.0,1.0,5.0,0.0,0.0,1.0,61.0,81.0
2,43261,2019,Geelong Cats,False,1,5.0,3.0,6.0,11.0,1.0,...,6.0,8.0,0.0,1.0,3.0,0.0,0.0,6.0,74.0,83.0
3,43261,2020,St Kilda Saints,False,1,2.0,2.0,1.0,3.0,1.0,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,6.0,22.0,54.0
4,43262,2002,Geelong Cats,False,12,37.0,13.0,63.0,100.0,10.0,...,5.7,3.0,0.3,0.3,1.0,0.2,0.0,5.3,36.9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25486,ID_43738,2013,Greater Western Sydney Giants,False,1,3.0,1.0,1.0,4.0,0.0,...,2.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,30.0,85.0
25487,ID_43660,2015,Carlton Blues,False,22,216.0,75.0,262.0,478.0,0.0,...,8.4,13.2,0.3,0.0,1.2,0.2,0.2,0.1,79.6,90.5
25488,ID_46153,2025,Melbourne Demons,False,5,15.0,5.0,12.0,27.0,3.0,...,3.4,1.8,0.4,0.8,2.8,0.0,0.4,4.2,30.8,62.4
25489,ID_44965,2005,Fremantle Dockers,False,6,30.0,11.0,41.0,71.0,1.0,...,4.8,7.2,0.0,0.2,1.8,0.2,0.0,1.3,41.5,47.8
25490,ID_45608,1998,carlton blues,False,15,117.0,24.0,97.0,214.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.7,47.4,NaN

**Check the number of rows and columns**

In [340]:
df1.shape

(2848, 16)

In [341]:
df2.shape

(25491, 54)

**See top 5 rows of each dataset**

In [342]:
df1.head()

,id,player_name,player_full_name,first_name,last_name,born_date,debut_date,debut_age,last_date,last_age,height,weight,profile_pic,player_link,player_common_names,player_teams
0,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,200,100,NaN,https://afltables.com/afl/stats/players/R/Ryan...,NaN,"{Geelong Cats,St Kilda Saints}"
1,43262,Gary Ablett,Gary_Ablett1,Gary,Ablett,1984-05-14,2002-03-30,17,2020-10-24,36,182,87,NaN,https://afltables.com/afl/stats/players/G/Gary...,NaN,"{Geelong Cats,Gold Coast Suns}"
2,43276,Leek Aleer,Leek_Aleer,Leek,Aleer,2001-08-21,2022-07-30,20,2025-09-06,24,195,85,https://res.cloudinary.com/dijzdikkh/image/upl...,https://afltables.com/afl/stats/players/L/Leek...,NaN,NaN
3,43264,Nathan Ablett,Nathan_Ablett,Nathan,Ablett,1985-12-13,2005-08-12,19,2011-08-28,25,195,95,NaN,https://afltables.com/afl/stats/players/N/Nath...,NaN,"{Geelong Cats,Gold Coast Suns}"
4,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,196,101,NaN,https://afltables.com/afl/stats/players/C/Cain...,NaN,"{Carlton Blues,Port Adelaide Power,St Kilda Sa..."

In [343]:
df2.head()

,player_id,year,team,is_finals,games_played,kicks,marks,handballs,disposals,goals,...,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_marks_inside_50,avg_one_percenters,avg_bounces,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played
0,43261,2018,Geelong Cats,False,3,17.0,9.0,21.0,38.0,3.0,...,6.7,6.7,0.3,1.7,4.3,0.0,0.3,6.7,92.7,84.3
1,43261,2018,Geelong Cats,True,1,3.0,2.0,2.0,5.0,0.0,...,2.0,3.0,1.0,1.0,5.0,0.0,0.0,1.0,61.0,81.0
2,43261,2019,Geelong Cats,False,1,5.0,3.0,6.0,11.0,1.0,...,6.0,8.0,0.0,1.0,3.0,0.0,0.0,6.0,74.0,83.0
3,43261,2020,St Kilda Saints,False,1,2.0,2.0,1.0,3.0,1.0,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,6.0,22.0,54.0
4,43262,2002,Geelong Cats,False,12,37.0,13.0,63.0,100.0,10.0,...,5.7,3.0,0.3,0.3,1.0,0.2,0.0,5.3,36.9,NaN

**Check duplicate rows in both dataset**

In [344]:
df1.duplicated().sum()

np.int64(5)

In [345]:
df2.duplicated().sum()

np.int64(10)

**Check missing values in both dataset**

In [346]:
df1.isnull().sum()

id                        0
player_name               0
player_full_name          0
first_name                0
last_name                 0
born_date                 0
debut_date                0
debut_age                 0
last_date                 0
last_age                  0
height                    0
weight                    0
profile_pic            2211
player_link               0
player_common_names    2773
player_teams             94
dtype: int64

In [347]:
df2.isnull().sum()

player_id                         0
year                              0
team                              0
is_finals                         0
games_played                      0
kicks                            52
marks                           185
handballs                       113
disposals                        24
goals                          2537
behinds                        2689
hit_outs                       5706
tackles                         511
rebound_50s                    3533
inside_50s                     2971
clearances                     3435
clangers                       2938
free_kicks_for                 1073
free_kicks_against              978
brownlow_votes                 6997
contested_possessions          3336
uncontested_possessions        3322
contested_marks                4925
marks_inside_50                5165
one_percenters                 3643
bounces                        5654
goal_assists                   7092
total_score                       0
total_fantasy_points              0
total_percentage_played        6246
avg_kicks                        52
avg_marks                       185
avg_handballs                   113
avg_disposals                    24
avg_goals                      2537
avg_behinds                    2689
avg_hit_outs                   5706
avg_tackles                     511
avg_rebound_50s                3533
avg_inside_50s                 2971
avg_clearances                 3435
avg_clangers                   2938
avg_free_kicks_for             1073
avg_free_kicks_against          978
avg_contested_possessions      3336
avg_uncontested_possessions    3322
avg_contested_marks            4925
avg_marks_inside_50            5165
avg_one_percenters             3643
avg_bounces                    5654
avg_goal_assists               7092
avg_score                         0
avg_fantasy_points                0
avg_percentage_played          6246
dtype: int64

**Check data types in both dataset**

In [348]:
df1.dtypes

id                      int64
player_name            object
player_full_name       object
first_name             object
last_name              object
born_date              object
debut_date             object
debut_age               int64
last_date              object
last_age                int64
height                  int64
weight                  int64
profile_pic            object
player_link            object
player_common_names    object
player_teams           object
dtype: object

In [349]:
df2.dtypes

player_id                       object
year                             int64
team                            object
is_finals                         bool
games_played                     int64
kicks                          float64
marks                          float64
handballs                      float64
disposals                      float64
goals                          float64
behinds                        float64
hit_outs                       float64
tackles                        float64
rebound_50s                    float64
inside_50s                     float64
clearances                     float64
clangers                       float64
free_kicks_for                 float64
free_kicks_against             float64
brownlow_votes                 float64
contested_possessions          float64
uncontested_possessions        float64
contested_marks                float64
marks_inside_50                float64
one_percenters                 float64
bounces                        float64
goal_assists                   float64
total_score                      int64
total_fantasy_points             int64
total_percentage_played        float64
avg_kicks                      float64
avg_marks                      float64
avg_handballs                  float64
avg_disposals                  float64
avg_goals                      float64
avg_behinds                    float64
avg_hit_outs                   float64
avg_tackles                    float64
avg_rebound_50s                float64
avg_inside_50s                 float64
avg_clearances                 float64
avg_clangers                   float64
avg_free_kicks_for             float64
avg_free_kicks_against         float64
avg_contested_possessions      float64
avg_uncontested_possessions    float64
avg_contested_marks            float64
avg_marks_inside_50            float64
avg_one_percenters             float64
avg_bounces                    float64
avg_goal_assists               float64
avg_score                      float64
avg_fantasy_points             float64
avg_percentage_played          float64
dtype: object

**Cleaning df1 dataset**

**Making copy of df1 dataset**

In [350]:
df1_clean = df1.copy()

**Removing text spaces from text columns**

In [351]:
for col in df1_clean.select_dtypes(include="object").columns:
    df1_clean[col] = df1_clean[col].apply(
        lambda x: x.strip() if isinstance(x, str) else x
    )

**Count rows before cleaning**

In [352]:
df1_before = len(df1_clean)

print("Rows before cleaning:", df1_before)

Rows before cleaning: 2848

**Count duplicate rows and remove them**

In [353]:
duplicate_count = df1_clean.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 5

In [354]:
df1_clean = df1_clean.drop_duplicates()
print("Duplicate rows removed:", duplicate_count)

Duplicate rows removed: 5

**Rows after cleaning**

In [355]:
print("Rows after cleaning:", len(df1_clean))

Rows after cleaning: 2843

**Covert ID into Numeric**

In [356]:
df1_clean["id"] = pd.to_numeric(
    df1_clean["id"],
    errors="coerce"
)

**convert into int**

In [357]:
df1_clean["id"] = df1_clean["id"].astype("Int64")

**Convert date columns into datetime dtype**

In [358]:
df1_clean["born_date"] = pd.to_datetime(
    df1_clean["born_date"],
    errors="coerce"
)

df1_clean["debut_date"] = pd.to_datetime(
    df1_clean["debut_date"],
    errors="coerce"
)

df1_clean["last_date"] = pd.to_datetime(
    df1_clean["last_date"],
    errors="coerce"
)

**check ivalid weight count**

In [359]:
invalid_weight_count = (df1_clean["weight"] <= 0).sum()

print("Invalid weights:", invalid_weight_count)

Invalid weights: 2

In [360]:
df1_clean.loc[df1_clean["weight"] <= 0, "weight"] = np.nan
print("Invalid weights fixed:", invalid_weight_count)

Invalid weights fixed: 2

**Finding mediam weight and fill with median**

In [361]:
weight_median = df1_clean["weight"].median()

print("Median weight:", weight_median)

df1_clean["weight"] = df1_clean["weight"].fillna(weight_median)

Median weight: 85.0

**Handeling missing profile pic**

In [362]:
df1_clean["profile_pic"] = df1_clean["profile_pic"].fillna("Not available")

**Handeling missing common names**

In [363]:
df1_clean["player_common_names"] = df1_clean["player_common_names"].fillna("None")

**Handeling missing team info**

In [364]:
df1_clean["player_teams"] = df1_clean["player_teams"].fillna("Not available")

**DF1 after handling missing values now 0 null values**

In [365]:
print("Players Info — missing values after cleaning:")

display(df1_clean.isna().sum().sort_values(ascending=False).to_frame("missing"))

Players Info — missing values after cleaning:

                     missing
id                         0
player_name                0
player_full_name           0
first_name                 0
last_name                  0
born_date                  0
debut_date                 0
debut_age                  0
last_date                  0
last_age                   0
height                     0
weight                     0
profile_pic                0
player_link                0
player_common_names        0
player_teams               0

**Checking again datatypes**

In [366]:
print("Players Info — final data types:")

display(df1_clean.dtypes.to_frame("dtype"))

Players Info — final data types:

                              dtype
id                            Int64
player_name                  object
player_full_name             object
first_name                   object
last_name                    object
born_date            datetime64[ns]
debut_date           datetime64[ns]
debut_age                     int64
last_date            datetime64[ns]
last_age                      int64
height                        int64
weight                      float64
profile_pic                  object
player_link                  object
player_common_names          object
player_teams                 object

**Save cleaned Players dataset**

In [367]:
df1_clean.to_csv("cleaned_players_info.csv", index=False)

**Cleaning df2 dataset**

**Making copy of df2 dataset**

In [368]:
df2_clean = df2.copy()

**Rows before cleaning**

In [369]:
df2_before = len(df2_clean)

print("Rows before cleaning:", df2_before)

Rows before cleaning: 25491

**Check duplicate rows**

In [370]:
df2_duplicates = df2_clean.duplicated().sum()

print("Duplicate rows:", df2_duplicates)

Duplicate rows: 10

**Remove extra spaces from text columns**

In [371]:
for col in df2_clean.select_dtypes(include="object").columns:
    df2_clean[col] = df2_clean[col].apply(
        lambda x: x.strip() if isinstance(x, str) else x
    )

**Clean player_id**

In [372]:
df2_clean["player_id"] = (
    df2_clean["player_id"]
    .astype(str)
    .str.extract(r"(\d+)")[0]
)

**Convert player_id to integer**

In [373]:
df2_clean["player_id"] = pd.to_numeric(
    df2_clean["player_id"],
    errors="coerce"
).astype("Int64")

**Convert year to integer**

In [374]:
df2_clean["year"] = pd.to_numeric(
    df2_clean["year"],
    errors="coerce"
).astype("Int64")

**Remove duplicate rows**

In [375]:
df2_clean = df2_clean.drop_duplicates().copy()

**Check invalid negative games**

In [376]:
invalid_games = (
    df2_clean["games_played"] < 0
).sum()

print("Invalid negative games:", invalid_games)

Invalid negative games: 4

**Remove negative games**

In [377]:
df2_clean = df2_clean[
    df2_clean["games_played"] >= 0
].copy()

**Check negative fantasy points**

In [378]:
print(df2_clean["total_fantasy_points"].dtype)

int64

In [379]:
print("Negative values:")
display(
    df2_clean[df2_clean["total_fantasy_points"] < 0][
        ["player_id", "year", "games_played", "avg_fantasy_points", "total_fantasy_points"]
    ]
)

Negative values:

       player_id  year  games_played  avg_fantasy_points  total_fantasy_points
344        45896  1998             1                -3.0                    -3
3302       43812  2013             1                -6.0                    -6
7215       44401  2022             1                -3.0                    -3
10017      44846  2021             1                -2.0                    -2
11860      45147  2019             1                -1.0                    -1
15754      45632  1999             1                -3.0                    -3
19511      46095  2013             1                -6.0                    -6
21704      45744  2003             1                -4.0                    -4
23614      45756  2007             1                -1.0                    -1
23773      45945  2001             1                -2.0                    -2

In [409]:
df2_clean.loc[
    df2_clean["total_fantasy_points"] < 0,
    "total_fantasy_points"
] = 0

**Replace negative fantasy points with missing value**

In [381]:
df2_clean.loc[
    df2_clean["avg_fantasy_points"] < 0,
    "avg_fantasy_points"
] = 0

In [410]:
df2_clean["total_fantasy_points"] = df2_clean[
    "total_fantasy_points"
].fillna(
    df2_clean["avg_fantasy_points"] * df2_clean["games_played"]
)

**List the total/count columns & Convert these columns to numeric**

In [411]:
count_total_cols = [
    "kicks",
    "marks",
    "handballs",
    "disposals",
    "goals",
    "behinds",
    "hit_outs",
    "tackles",
    "rebound_50s",
    "inside_50s",
    "clearances",
    "clangers",
    "free_kicks_for",
    "free_kicks_against",
    "brownlow_votes",
    "contested_possessions",
    "uncontested_possessions",
    "contested_marks",
    "marks_inside_50",
    "one_percenters",
    "bounces",
    "goal_assists",
    "total_score"
]
for col in count_total_cols:
    df2_clean[col] = pd.to_numeric(
        df2_clean[col],
        errors="coerce"
    )

**Fill missing values with 0**

These are count/total statistics, so missing values are treated as zero according to our cleaning rule.

In [412]:
for col in count_total_cols:
    df2_clean[col] = df2_clean[col].fillna(0)

**Convert total percentage played to numeric**

In [413]:
df2_clean["total_percentage_played"] = pd.to_numeric(
    df2_clean["total_percentage_played"],
    errors="coerce"
)

**Fill missing percentage played and remaining with 0**

In [414]:
df2_clean["total_percentage_played"] = (
    df2_clean["total_percentage_played"]
    .fillna(
        df2_clean["avg_percentage_played"] *
        df2_clean["games_played"]
    )
)

In [415]:
df2_clean["total_percentage_played"] = (
    df2_clean["total_percentage_played"]
    .fillna(0)
)

**Define average columns**

In [416]:
avg_to_total = {
    "avg_kicks": "kicks",
    "avg_marks": "marks",
    "avg_handballs": "handballs",
    "avg_disposals": "disposals",
    "avg_goals": "goals",
    "avg_behinds": "behinds",
    "avg_hit_outs": "hit_outs",
    "avg_tackles": "tackles",
    "avg_rebound_50s": "rebound_50s",
    "avg_inside_50s": "inside_50s",
    "avg_clearances": "clearances",
    "avg_clangers": "clangers",
    "avg_free_kicks_for": "free_kicks_for",
    "avg_free_kicks_against": "free_kicks_against",
    "avg_contested_possessions": "contested_possessions",
    "avg_uncontested_possessions": "uncontested_possessions",
    "avg_contested_marks": "contested_marks",
    "avg_marks_inside_50": "marks_inside_50",
    "avg_one_percenters": "one_percenters",
    "avg_bounces": "bounces",
    "avg_goal_assists": "goal_assists",
    "avg_score": "total_score",
    "avg_fantasy_points": "total_fantasy_points",
    "avg_percentage_played": "total_percentage_played"
}

**Recalculate averages**

In [417]:
for avg_col, total_col in avg_to_total.items():

    df2_clean[avg_col] = np.where(
        df2_clean["games_played"] > 0,
        df2_clean[total_col] /
        df2_clean["games_played"],
        0
    ).round(1)

**Standardize team names**

In [418]:
df2_clean["team"] = (
    df2_clean["team"]
    .astype(str)
    .str.strip()
    .str.title()
)

**Check missing values after cleaning**

In [419]:
print("Missing values after cleaning:")

display(
    df2_clean.isna()
    .sum()
    .sort_values(ascending=False)
    .to_frame("missing")
)

Missing values after cleaning:

                             missing
player_id                          0
year                               0
team                               0
is_finals                          0
games_played                       0
kicks                              0
marks                              0
handballs                          0
disposals                          0
goals                              0
behinds                            0
hit_outs                           0
tackles                            0
rebound_50s                        0
inside_50s                         0
clearances                         0
clangers                           0
free_kicks_for                     0
free_kicks_against                 0
brownlow_votes                     0
contested_possessions              0
uncontested_possessions            0
contested_marks                    0
marks_inside_50                    0
one_percenters                     0
bounces                            0
goal_assists                       0
total_score                        0
total_fantasy_points               0
total_percentage_played            0
avg_kicks                          0
avg_marks                          0
avg_handballs                      0
avg_disposals                      0
avg_goals                          0
avg_behinds                        0
avg_hit_outs                       0
avg_tackles                        0
avg_rebound_50s                    0
avg_inside_50s                     0
avg_clearances                     0
avg_clangers                       0
avg_free_kicks_for                 0
avg_free_kicks_against             0
avg_contested_possessions          0
avg_uncontested_possessions        0
avg_contested_marks                0
avg_marks_inside_50                0
avg_one_percenters                 0
avg_bounces                        0
avg_goal_assists                   0
avg_score                          0
avg_fantasy_points                 0
avg_percentage_played              0

**Check final data types**

In [420]:
print("Final data types:")

display(
    df2_clean.dtypes.to_frame("dtype")
)

Final data types:

                               dtype
player_id                      int64
year                           int64
team                          object
is_finals                       bool
games_played                   int64
kicks                        float64
marks                        float64
handballs                    float64
disposals                    float64
goals                        float64
behinds                      float64
hit_outs                     float64
tackles                      float64
rebound_50s                  float64
inside_50s                   float64
clearances                   float64
clangers                     float64
free_kicks_for               float64
free_kicks_against           float64
brownlow_votes               float64
contested_possessions        float64
uncontested_possessions      float64
contested_marks              float64
marks_inside_50              float64
one_percenters               float64
bounces                      float64
goal_assists                 float64
total_score                    int64
total_fantasy_points         float64
total_percentage_played      float64
avg_kicks                    float64
avg_marks                    float64
avg_handballs                float64
avg_disposals                float64
avg_goals                    float64
avg_behinds                  float64
avg_hit_outs                 float64
avg_tackles                  float64
avg_rebound_50s              float64
avg_inside_50s               float64
avg_clearances               float64
avg_clangers                 float64
avg_free_kicks_for           float64
avg_free_kicks_against       float64
avg_contested_possessions    float64
avg_uncontested_possessions  float64
avg_contested_marks          float64
avg_marks_inside_50          float64
avg_one_percenters           float64
avg_bounces                  float64
avg_goal_assists             float64
avg_score                    float64
avg_fantasy_points           float64
avg_percentage_played        float64

**Save cleaned Seasonal Stats dataset**

In [421]:
df2_clean.to_csv("cleaned_seasonal_stats.csv", index=False)

**Data Quslity report**

In [422]:
df1          # original Players dataset
df1_clean    # cleaned Players dataset

df2          # original Seasonal Stats dataset
df2_clean    # cleaned Seasonal Stats dataset

,player_id,year,team,is_finals,games_played,kicks,marks,handballs,disposals,goals,...,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_marks_inside_50,avg_one_percenters,avg_bounces,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played
0,43261,2018,Geelong Cats,False,3,17.0,9.0,21.0,38.0,3.0,...,6.7,6.7,0.3,1.7,4.3,0.0,0.3,6.7,92.7,84.3
1,43261,2018,Geelong Cats,True,1,3.0,2.0,2.0,5.0,0.0,...,2.0,3.0,1.0,1.0,5.0,0.0,0.0,1.0,61.0,81.0
2,43261,2019,Geelong Cats,False,1,5.0,3.0,6.0,11.0,1.0,...,6.0,8.0,0.0,1.0,3.0,0.0,0.0,6.0,74.0,83.0
3,43261,2020,St Kilda Saints,False,1,2.0,2.0,1.0,3.0,1.0,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,6.0,22.0,54.0
4,43262,2002,Geelong Cats,False,12,37.0,13.0,63.0,100.0,10.0,...,5.7,3.0,0.2,0.2,1.0,0.2,0.0,5.2,36.9,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25472,43738,2013,Greater Western Sydney Giants,False,1,3.0,1.0,1.0,4.0,0.0,...,2.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,30.0,85.0
25473,43660,2015,Carlton Blues,False,22,216.0,75.0,262.0,478.0,0.0,...,8.4,13.2,0.3,0.0,1.2,0.2,0.2,0.1,79.6,90.5
25474,46153,2025,Melbourne Demons,False,5,15.0,5.0,12.0,27.0,3.0,...,3.4,1.8,0.4,0.8,2.8,0.0,0.4,4.2,30.8,62.4
25475,44965,2005,Fremantle Dockers,False,6,30.0,11.0,41.0,71.0,1.0,...,4.8,7.2,0.0,0.2,1.8,0.2,0.0,1.3,41.5,47.8
25476,45608,1998,Carlton Blues,False,15,117.0,24.0,97.0,214.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.7,47.4,0.0

In [423]:
data_quality_report = pd.DataFrame({

    "Dataset": [
        "Players Info",
        "Players Info",
        "Players Info",
        "Seasonal Stats",
        "Seasonal Stats",
        "Seasonal Stats",
        "Seasonal Stats"
    ],

    "Issue": [
        "Duplicate rows",
        "Invalid weight",
        "Missing optional fields",
        "Duplicate rows",
        "Negative games played",
        "Negative fantasy points",
        "Missing statistical values"
    ],

    "Count": [
        df1.duplicated().sum(),
        (df1["weight"] <= 0).sum(),
        df1[["profile_pic", "player_common_names", "player_teams"]].isna().sum().sum(),
        df2.duplicated().sum(),
        (df2["games_played"] < 0).sum(),
        (df2["total_fantasy_points"] < 0).sum(),
        df2.isna().sum().sum()
    ],

    "Action Taken": [
        "Removed duplicates",
        "Replaced with median",
        "Filled with labels",
        "Removed duplicates",
        "Removed rows",
        "Recalculated values",
        "Handled missing values"
    ],

    "Reason": [
        "Avoid duplicate player records",
        "Weight cannot be zero or negative",
        "These fields are optional",
        "Avoid duplicate statistics",
        "Games played cannot be negative",
        "Fantasy points cannot be negative",
        "Missing data can affect analysis"
    ]
})

display(data_quality_report)

,Dataset,Issue,Count,Action Taken,Reason
0,Players Info,Duplicate rows,5,Removed duplicates,Avoid duplicate player records
1,Players Info,Invalid weight,2,Replaced with median,Weight cannot be zero or negative
2,Players Info,Missing optional fields,5078,Filled with labels,These fields are optional
3,Seasonal Stats,Duplicate rows,10,Removed duplicates,Avoid duplicate statistics
4,Seasonal Stats,Negative games played,8,Removed rows,Games played cannot be negative
5,Seasonal Stats,Negative fantasy points,10,Recalculated values,Fantasy points cannot be negative
6,Seasonal Stats,Missing statistical values,139253,Handled missing values,Missing data can affect analysis

**Merging**

**Load clean datasets**

In [396]:
import pandas as pd

df1_clean = pd.read_csv("/content/cleaned_players_info.csv")
df2_clean = pd.read_csv("/content/cleaned_seasonal_stats.csv")

print("Players Info:", df1_clean.shape)
print("Seasonal Stats:", df2_clean.shape)

Players Info: (2843, 16)
Seasonal Stats: (25477, 54)

In [424]:
df1_clean["id"] = pd.to_numeric(df1_clean["id"], errors="coerce")
df2_clean["player_id"] = pd.to_numeric(df2_clean["player_id"], errors="coerce")

In [425]:
player_ids = set(df1_clean["id"].dropna())
stats_ids = set(df2_clean["player_id"].dropna())

unmatched_ids = sorted(stats_ids - player_ids)

print("Unique IDs in Players Info:", len(player_ids))
print("Unique IDs in Seasonal Stats:", len(stats_ids))
print("Unmatched player IDs:", len(unmatched_ids))

print("\nFirst 50 unmatched IDs:")
print(unmatched_ids[:50])

Unique IDs in Players Info: 2843
Unique IDs in Seasonal Stats: 3108
Unmatched player IDs: 266

First 50 unmatched IDs:
[43280, 43292, 43299, 43319, 43325, 43329, 43332, 43348, 43359, 43361, 43363, 43364, 43365, 43378, 43379, 43396, 43410, 43420, 43426, 43433, 43440, 43472, 43478, 43503, 43511, 43533, 43546, 43547, 43552, 43568, 43571, 43572, 43574, 43575, 43583, 43587, 43588, 43594, 43600, 43607, 43616, 43626, 43644, 43650, 43670, 43671, 43688, 43697, 43705, 43715]

In [426]:
merged_players = df2_clean.merge(
    df1_clean,
    left_on="player_id",
    right_on="id",
    how="inner"
)

merged_players = merged_players.drop_duplicates()

merged_players.to_csv(
    "/content/merged_players.csv",
    index=False
)

print("Final merged CSV saved!")

Final merged CSV saved!

**Check duplicates after merging**

In [427]:
print("Duplicate rows:", merged_players.duplicated().sum())

Duplicate rows: 0

**Checking null values of merged dataset**

In [428]:
print("Null values after merge:")

display(
    merged_players.isna().sum().sort_values(ascending=False)
)

Null values after merge:

player_common_names    24169
player_id                  0
team                       0
is_finals                  0
games_played               0
                       ...
last_age                   0
weight                     0
profile_pic                0
player_link                0
player_teams               0
Length: 70, dtype: int64

In [429]:
merged_players["player_common_names"] = (
    merged_players["player_common_names"].fillna("None")
)

In [430]:
merged_players.isnull().sum()

player_id              0
year                   0
team                   0
is_finals              0
games_played           0
                      ..
weight                 0
profile_pic            0
player_link            0
player_common_names    0
player_teams           0
Length: 70, dtype: int64

In [431]:
print("Final merged rows:", len(merged_players))
print("Total null values:", merged_players.isna().sum().sum())
print("Duplicate rows:", merged_players.duplicated().sum())

Final merged rows: 25077
Total null values: 0
Duplicate rows: 0

In [432]:
merged_players.to_csv(
    "/content/merged_players.csv",
    index=False
)

print("merged_players.csv saved successfully!")

merged_players.csv saved successfully!

In [406]:
from google.colab import files

files.download("/content/merged_players.csv")

**Validation report**

In [433]:
validation_report = pd.DataFrame([

    ["Players Info", "Rows before cleaning", 2848],
    ["Players Info", "Rows after cleaning", len(df1_clean)],
    ["Players Info", "Duplicate rows removed", 5],
    ["Players Info", "Remaining missing cells", int(df1_clean.isna().sum().sum())],

    ["Seasonal Stats", "Rows before cleaning", 25491],
    ["Seasonal Stats", "Rows after cleaning", len(df2_clean)],
    ["Seasonal Stats", "Duplicate rows removed", 10],
    ["Seasonal Stats", "Invalid games rows removed", 4],
    ["Seasonal Stats", "Negative fantasy values repaired", 10],
    ["Seasonal Stats", "Remaining missing cells", int(df2_clean.isna().sum().sum())],

    ["Merge", "Seasonal-stat rows before merge", len(df2_clean)],
    ["Merge", "Matched rows in final dataset", len(merged_players)],
    ["Merge", "Unmatched player_id rows", 400],
    ["Merge", "Unmatched unique player_id values", 266],
    ["Merge", "Duplicate rows after merge", int(merged_players.duplicated().sum())]

], columns=["Stage", "Validation item", "Value"])


display(validation_report)

             Stage                    Validation item  Value
0     Players Info               Rows before cleaning   2848
1     Players Info                Rows after cleaning   2843
2     Players Info             Duplicate rows removed      5
3     Players Info            Remaining missing cells   2768
4   Seasonal Stats               Rows before cleaning  25491
5   Seasonal Stats                Rows after cleaning  25477
6   Seasonal Stats             Duplicate rows removed     10
7   Seasonal Stats         Invalid games rows removed      4
8   Seasonal Stats   Negative fantasy values repaired     10
9   Seasonal Stats            Remaining missing cells      0
10           Merge    Seasonal-stat rows before merge  25477
11           Merge      Matched rows in final dataset  25077
12           Merge           Unmatched player_id rows    400
13           Merge  Unmatched unique player_id values    266
14           Merge         Duplicate rows after merge      0

In [434]:
print(
    "No duplicate rows in Players Info:",
    not df1_clean.duplicated().any()
)

print(
    "No duplicate rows in Seasonal Stats:",
    not df2_clean.duplicated().any()
)

print(
    "No negative games played:",
    (df2_clean["games_played"] >= 0).all()
)

print(
    "No negative fantasy points:",
    (df2_clean["total_fantasy_points"] >= 0).all()
)

print(
    "All merged player IDs matched:",
    set(merged_players["player_id"].dropna()).issubset(
        set(df1_clean["id"].dropna())
    )
)

No duplicate rows in Players Info: True
No duplicate rows in Seasonal Stats: True
No negative games played: True
No negative fantasy points: True
All merged player IDs matched: True